# -*- coding: utf-8 -*-
"""proyecto integrador battleship programacion idm1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6HHExHp0np0uBuPbSSSMwUMPaFbTEDq
"""

#Se define la primera función la cual va a saludar al usuario y le va a explicar como se juega Battleship.
def bienvenida():
  print("---------------------------\n"
      "        BATTLESHIP\n"
      "---------------------------\n")
  print('Battleship es un juego de mesa para dos jugadores en el que intentan adivinar la ubicación de los barcos del otro jugador en un tablero.')

  print("--------------------------- -----------------------------------------------------------------------------------------------------------")
  print('¿Cómo jugar?')
  print('1. cada jugador coloca sus barcos en el tablero de forma oculta al otro jugador.')
  print('2. Los jugadores se turnan para adivinar la ubicación de los barcos del otro jugador.')
  print("**************************************************************************************************************************************")
  print('Para adivinar, un jugador dice la coordenada de una casilla del tablero. ')
  print('Si hay un barco en esa casilla, el barco se hunde y el jugador que lo hundió gana un punto.')
  print('Si no hay un barco en esa casilla, el jugador pierde su turno.')
  print("**************************************************************************************************************************************")
  print('3. El juego continúa hasta que un jugador hunde todos los barcos del otro jugador.')
  print('4. El primer jugador en hundir todos los barcos del otro jugador gana la partida.')
  print('5. ¡Diviértete!')
  print("--------------------------- -----------------------------------------------------------------------------------------------------------\n")

def verifica_fila():
  disparo_fila=input("Ingrese la fila de su disparo(1-9): ")
  if disparo_fila not in ["1","2","3","4","5","6","7","8","9"]:
    print("Error.")
    condicion=True
    while condicion==True:
      disparo_fila=input("Ingrese la fila de su disparo(1-9): ")
      if disparo_fila in ["1","2","3","4","5","6","7","8","9"]:
        condicion=False
        disparo_fila=int(disparo_fila)
      else:
        print("Error")
        condicion=True
  else:
    disparo_fila=int(disparo_fila)
  return disparo_fila

def verifica_columna():
  disparo_columna=input("Ingrese la columna de su disparo(1-9): ")
  if disparo_columna not in ["1","2","3","4","5","6","7","8","9"]:
    print("Error.")
    condicion=True
    while condicion==True:
      disparo_columna=input("Ingrese la columna de su disparo(1-9): ")
      if disparo_columna in ["1","2","3","4","5","6","7","8","9"]:
        condicion=False
        disparo_columna=int(disparo_columna)
      else:
        print("Error")
        condicion=True
  else:
    disparo_columna=int(disparo_columna)
  return disparo_columna

import random
def tablero():
  matriz = [[" " for x in range(9)] for y in range(9)]
  primera_fila = [str(x) for x in range(9)]
  num_fila=1
  column=1
  print("  1 2 3 4 5 6 7 8 9")
  for fila in matriz:
    print("%d|%s|"%(num_fila,"|".join(fila)))
    num_fila+=1
def colocar_barcos():
  posiciones_barcos = set()
  for i in range(5):
    posicion_barco_fila = random.randint(1,9)
    posicion_barco_columna = random.randint(1,9)
    posicion_barco= (posicion_barco_fila,posicion_barco_columna)
    if posicion_barco not in posiciones_barcos:
      posiciones_barcos.add(posicion_barco)
  print(posiciones_barcos)
  return posiciones_barcos
def disparos(posiciones_barcos):
  num_intentos = 10
  posiciones_barcos = colocar_barcos()
  barcos = 5
  barcos_derribados = 0
  matriz = tablero()
  posicion_disparos = set()
  while barcos>0 and num_intentos>0:
    disparo_fila = verifica_fila()
    disparo_columna = verifica_columna()
    disparo = (disparo_fila,disparo_columna)
    if disparo not in posicion_disparos:
      num_intentos -= 1
      if disparo in posiciones_barcos:
        barcos -= 1
        barcos_derribados +=1
        print(f"HAS DERRIBADO UN BARCO ENEMIGO. SIGUE ASÍ, TE QUEDAN {num_intentos} INTENTOS. HAY {barcos} BARCOS EN PIE.")
      elif disparo not in posiciones_barcos:
        print(f"HAS FALLADO, INTÉNTALO DE NUEVO, TE QUEDAN {num_intentos} INTENTOS. HAY {barcos} BARCOS EN PIE.")
    elif disparo in posicion_disparos:
      print("Ya has disparado a esta ubicación, intenta disparando a otra ubicación")
    posicion_disparos.add(disparo)
  if num_intentos == 0:
    print(f"SE HAN ACABADO TUS INTENTOS. DERRIBASTE {barcos_derribados} BARCOS.")
  if barcos==0:
    print("FELICIDADES! HAS GANADO EL JUEGO! DERRIBASTE TODOS LOS BARCOS ENEMIGOS!")
  elif barcos>0:
    print("SIGUE INTENTANDO A LA PRÓXIMA.")

def main():
  while True:
    eleccion = str(input("Ingrese su elección (1=JUGAR, 2=SALIR): "))
    if eleccion == "2" or eleccion =="Salir":
      print("Ha salido del juego")
      break
    if eleccion == "1" or eleccion =="Jugar":
      bienvenida()
      tablero()
      colocar_barcos()
      disparos(colocar_barcos)



main()